import mpaStatusData from "@/data/mpa-status.json";
import type { MpaGuideAssessment, MpaStatus } from "./types";

/**
 * Standalone MPAtlas protection for a location that has NO editorial
 * reef-pressure record. Generated by scripts/fetch-mpa-status.mjs from the
 * licensed MPA Guide download — pure assessment data, never invented pressure
 * or visitor copy. The app reads this as a fallback for mpaStatus so a location
 * whose centre sits in an assessed reserve still shows (and filters by) its real
 * protection level. A reef-pressure record, when present, always wins.
 */
export type StandaloneMpaStatus = {
  locationId: string;
  mpaStatus: MpaStatus;
  mpaStatusSource: "mpatlas";
  mpaAssessment?: MpaGuideAssessment;
  matchVia?: string;
  matchDistanceKm?: number;
  lastReviewedAt: string;
};

const records = mpaStatusData as StandaloneMpaStatus[];
const byLocationId = new Map<string, StandaloneMpaStatus>();
for (const r of records) byLocationId.set(r.locationId, r);

export const getStandaloneMpaStatus = (
  locationId: string,
): StandaloneMpaStatus | null => byLocationId.get(locationId) ?? null;
