import creditsData from "@/data/species-photo-credits.json";

/**
 * Photo provenance for a species. Generated by scripts/fetch-species-photos.mjs.
 * Keys are either:
 *   - legacy global key: lower-cased scientific or common name
 *   - per-site key: "{siteSlug}:{speciesKey}"
 * Fields vary by source (iNat regional, iNat taxa, Wikimedia).
 */
type RawCredit = {
  imageUrl: string;
  taxonId?: number;
  matchedName?: string;
  matchedCommon?: string | null;
  license?: string | null;
  attribution?: string | null;
  siteSlug?: string;
  speciesKey?: string;
  source?: string;
};

export type SpeciesPhotoCredit = {
  imageUrl: string;
  /** Best-effort photographer name parsed from the iNaturalist attribution. */
  photographer: string | null;
  /** Human label for the licence (e.g. "CC BY-NC", "© all rights reserved"). */
  licenseLabel: string;
};

const credits = creditsData as unknown as Record<string, RawCredit>;

const LICENSE_LABEL: Record<string, string> = {
  "cc-by": "CC BY",
  "cc-by-nc": "CC BY-NC",
  "cc-by-nc-sa": "CC BY-NC-SA",
  "cc-by-nc-nd": "CC BY-NC-ND",
  "cc-by-sa": "CC BY-SA",
  "cc-by-nd": "CC BY-ND",
  pd: "Public domain",
  cc0: "CC0",
};

/** iNat attribution reads like "(c) Jane Doe, some rights reserved (CC BY-NC), uploaded by …". */
function parsePhotographer(attribution: string | null): string | null {
  if (!attribution) return null;
  const m = attribution.match(/\(c\)\s*([^,]+)/i);
  return m ? m[1].trim() : null;
}

export function getSpeciesPhotoCredit(key: string): SpeciesPhotoCredit | null {
  const c = credits[key.trim().toLowerCase()];
  if (!c) return null;
  return {
    imageUrl: c.imageUrl,
    photographer: parsePhotographer(c.attribution ?? null),
    licenseLabel: c.license
      ? (LICENSE_LABEL[c.license] ?? c.license.toUpperCase())
      : "© all rights reserved",
  };
}
